//
//Copyright 2021, 2023 Ethan Blanton <eblanton@buffalo.edu>
//
//This file is part of a CSE 486/586 project from the University at
//Buffalo.  Distribution of this file or its associated repository
//requires the written permission of Ethan Blanton.  Sharing this file
//may be a violation of academic integrity, please consult the course
//policies for more information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: api/kdht/messages.proto

package kdht

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType indicates the type of a Message.  Different
// message types have different valid fields.
type MessageType int32

const (
	// PING request
	MessageType_PING MessageType = 0
	// STORE value at key
	MessageType_STORE MessageType = 1
	// GET a specific key's value
	MessageType_GET MessageType = 2
	// Request K closest nodes to a key
	MessageType_FIND_NODE MessageType = 3
	// Request value for a key, or K closest nodes
	MessageType_FIND_VALUE MessageType = 4
	// PING or STORE acknowledgment
	MessageType_ACK MessageType = 5
	// Reply to FIND_NODE or FIND_VALUE
	MessageType_NODES MessageType = 6
	// Reply to successful FIND_VALUE
	MessageType_VALUE MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PING",
		1: "STORE",
		2: "GET",
		3: "FIND_NODE",
		4: "FIND_VALUE",
		5: "ACK",
		6: "NODES",
		7: "VALUE",
	}
	MessageType_value = map[string]int32{
		"PING":       0,
		"STORE":      1,
		"GET":        2,
		"FIND_NODE":  3,
		"FIND_VALUE": 4,
		"ACK":        5,
		"NODES":      6,
		"VALUE":      7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kdht_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_api_kdht_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_kdht_messages_proto_rawDescGZIP(), []int{0}
}

// NodeInfo represents a node in the DHT.  It contains the node's
// listening TCP address and its 160-bit node ID.
//
// It is an error to send an Address that is not a valid string
// containing a node address that can be connected to with net.Dial(),
// and it is an error to send an ID field that is not exactly 160 bits
// long.
type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id      []byte `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kdht_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_kdht_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_kdht_messages_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// Message is the universal message type in a KDHT.  Every message
// includes a Sender and Type, and the Type determines which other
// fields are valid.  You must always send a well-formed Message,
// but we will not ever send in incorrect Message to your
// implementation.
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The sender of this message; both address and id must be present.
	Sender *NodeInfo `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// The type of this message
	Type MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=kdht.MessageType" json:"type,omitempty"`
	// Key is present for:
	// STORE: the key to store
	// GET: the key to retrieve
	// FIND_NODE: the node ID to find
	// FIND_VALUE: the key for the value to be retrieved
	// ACK: the key that was stored in a STORE or requested by GET (empty for PING ACK)
	// NODES: the key requested in FIND_NODE or FIND_VALUE
	// VALUE: the key requested in FIND_VALUE
	Key []byte `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value is present only for:
	// PING: an optional value may be sent for your debugging purposes
	// STORE: the value to store for this key
	// ACK: The value sent in a PING being acknowledged (empty for STORE ACK or GET (N)ACK)
	// VALUE: the value retrieved by a GET or FIND_VALUE
	Value []byte `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	// Nodes is the list of the K closest nodes to a requested key in
	// the response to a FIND_NODE or FIND_VALUE message (assuming
	// that the value was not found, in the latter case).
	Nodes []*NodeInfo `protobuf:"bytes,5,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kdht_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_kdht_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_kdht_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetSender() *NodeInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PING
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Message) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_api_kdht_messages_proto protoreflect.FileDescriptor

var file_api_kdht_messages_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x64, 0x68, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x64, 0x68, 0x74, 0x22,
	0x34, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa6, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x2a, 0x69,
	0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x4f, 0x52, 0x45,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x46,
	0x49, 0x4e, 0x44, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x49,
	0x4e, 0x44, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x43,
	0x4b, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x44, 0x45, 0x53, 0x10, 0x06, 0x12, 0x09,
	0x0a, 0x05, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x07, 0x42, 0x16, 0x5a, 0x14, 0x63, 0x73, 0x65,
	0x35, 0x38, 0x36, 0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x64, 0x68,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_kdht_messages_proto_rawDescOnce sync.Once
	file_api_kdht_messages_proto_rawDescData = file_api_kdht_messages_proto_rawDesc
)

func file_api_kdht_messages_proto_rawDescGZIP() []byte {
	file_api_kdht_messages_proto_rawDescOnce.Do(func() {
		file_api_kdht_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_kdht_messages_proto_rawDescData)
	})
	return file_api_kdht_messages_proto_rawDescData
}

var file_api_kdht_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_kdht_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_kdht_messages_proto_goTypes = []interface{}{
	(MessageType)(0), // 0: kdht.MessageType
	(*NodeInfo)(nil), // 1: kdht.NodeInfo
	(*Message)(nil),  // 2: kdht.Message
}
var file_api_kdht_messages_proto_depIdxs = []int32{
	1, // 0: kdht.Message.sender:type_name -> kdht.NodeInfo
	0, // 1: kdht.Message.type:type_name -> kdht.MessageType
	1, // 2: kdht.Message.Nodes:type_name -> kdht.NodeInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_kdht_messages_proto_init() }
func file_api_kdht_messages_proto_init() {
	if File_api_kdht_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_kdht_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_kdht_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_kdht_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_kdht_messages_proto_goTypes,
		DependencyIndexes: file_api_kdht_messages_proto_depIdxs,
		EnumInfos:         file_api_kdht_messages_proto_enumTypes,
		MessageInfos:      file_api_kdht_messages_proto_msgTypes,
	}.Build()
	File_api_kdht_messages_proto = out.File
	file_api_kdht_messages_proto_rawDesc = nil
	file_api_kdht_messages_proto_goTypes = nil
	file_api_kdht_messages_proto_depIdxs = nil
}
