//
//Copyright 2021, 2023 Ethan Blanton <eblanton@buffalo.edu>
//
//This file is part of a CSE 486/586 project from the University at
//Buffalo.  Distribution of this file or its associated repository
//requires the written permission of Ethan Blanton.  Sharing this file
//may be a violation of academic integrity, please consult the course
//policies for more information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: api/kdht/router.proto

package kdht

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteMessage int32

const (
	RouteMessage_NIL      RouteMessage = 0
	RouteMessage_MAX_SIZE RouteMessage = 65535
)

// Enum value maps for RouteMessage.
var (
	RouteMessage_name = map[int32]string{
		0:     "NIL",
		65535: "MAX_SIZE",
	}
	RouteMessage_value = map[string]int32{
		"NIL":      0,
		"MAX_SIZE": 65535,
	}
)

func (x RouteMessage) Enum() *RouteMessage {
	p := new(RouteMessage)
	*p = x
	return p
}

func (x RouteMessage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteMessage) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kdht_router_proto_enumTypes[0].Descriptor()
}

func (RouteMessage) Type() protoreflect.EnumType {
	return &file_api_kdht_router_proto_enumTypes[0]
}

func (x RouteMessage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteMessage.Descriptor instead.
func (RouteMessage) EnumDescriptor() ([]byte, []int) {
	return file_api_kdht_router_proto_rawDescGZIP(), []int{0}
}

type RouteType int32

const (
	RouteType_UNUSED      RouteType = 0
	RouteType_K           RouteType = 1
	RouteType_INSERT_NODE RouteType = 2
	RouteType_REMOVE_NODE RouteType = 3
	RouteType_LOOKUP      RouteType = 4
	RouteType_GET_NODES   RouteType = 5
	RouteType_CLOSEST_K   RouteType = 6
	RouteType_BUCKETS     RouteType = 7
	RouteType_INIT        RouteType = 8
)

// Enum value maps for RouteType.
var (
	RouteType_name = map[int32]string{
		0: "UNUSED",
		1: "K",
		2: "INSERT_NODE",
		3: "REMOVE_NODE",
		4: "LOOKUP",
		5: "GET_NODES",
		6: "CLOSEST_K",
		7: "BUCKETS",
		8: "INIT",
	}
	RouteType_value = map[string]int32{
		"UNUSED":      0,
		"K":           1,
		"INSERT_NODE": 2,
		"REMOVE_NODE": 3,
		"LOOKUP":      4,
		"GET_NODES":   5,
		"CLOSEST_K":   6,
		"BUCKETS":     7,
		"INIT":        8,
	}
)

func (x RouteType) Enum() *RouteType {
	p := new(RouteType)
	*p = x
	return p
}

func (x RouteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kdht_router_proto_enumTypes[1].Descriptor()
}

func (RouteType) Type() protoreflect.EnumType {
	return &file_api_kdht_router_proto_enumTypes[1]
}

func (x RouteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteType.Descriptor instead.
func (RouteType) EnumDescriptor() ([]byte, []int) {
	return file_api_kdht_router_proto_rawDescGZIP(), []int{1}
}

type RouteError int32

const (
	RouteError_NONE    RouteError = 0
	RouteError_INVALID RouteError = 1
	RouteError_STRING  RouteError = 2
)

// Enum value maps for RouteError.
var (
	RouteError_name = map[int32]string{
		0: "NONE",
		1: "INVALID",
		2: "STRING",
	}
	RouteError_value = map[string]int32{
		"NONE":    0,
		"INVALID": 1,
		"STRING":  2,
	}
)

func (x RouteError) Enum() *RouteError {
	p := new(RouteError)
	*p = x
	return p
}

func (x RouteError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteError) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kdht_router_proto_enumTypes[2].Descriptor()
}

func (RouteError) Type() protoreflect.EnumType {
	return &file_api_kdht_router_proto_enumTypes[2]
}

func (x RouteError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteError.Descriptor instead.
func (RouteError) EnumDescriptor() ([]byte, []int) {
	return file_api_kdht_router_proto_rawDescGZIP(), []int{2}
}

type RouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type RouteType `protobuf:"varint,1,opt,name=type,proto3,enum=kdht.RouteType" json:"type,omitempty"`
	Node *NodeInfo `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	I    int32     `protobuf:"varint,3,opt,name=i,proto3" json:"i,omitempty"`
	Key  []byte    `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kdht_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kdht_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_api_kdht_router_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetType() RouteType {
	if x != nil {
		return x.Type
	}
	return RouteType_UNUSED
}

func (x *RouteRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RouteRequest) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *RouteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  RouteType   `protobuf:"varint,1,opt,name=type,proto3,enum=kdht.RouteType" json:"type,omitempty"`
	Error RouteError  `protobuf:"varint,2,opt,name=error,proto3,enum=kdht.RouteError" json:"error,omitempty"`
	Str   string      `protobuf:"bytes,3,opt,name=str,proto3" json:"str,omitempty"`
	I     int32       `protobuf:"varint,4,opt,name=i,proto3" json:"i,omitempty"`
	Node  *NodeInfo   `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	Nodes []*NodeInfo `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kdht_router_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kdht_router_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_api_kdht_router_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetType() RouteType {
	if x != nil {
		return x.Type
	}
	return RouteType_UNUSED
}

func (x *RouteResponse) GetError() RouteError {
	if x != nil {
		return x.Error
	}
	return RouteError_NONE
}

func (x *RouteResponse) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *RouteResponse) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *RouteResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RouteResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_api_kdht_router_proto protoreflect.FileDescriptor

var file_api_kdht_router_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x64, 0x68, 0x74, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x64, 0x68, 0x74, 0x1a, 0x17, 0x61,
	0x70, 0x69, 0x2f, 0x6b, 0x64, 0x68, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2e, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x64, 0x68, 0x74,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12,
	0x0c, 0x0a, 0x01, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0xc6, 0x01, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72,
	0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x12, 0x22,
	0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b,
	0x64, 0x68, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2a, 0x27, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x49, 0x4c, 0x10,
	0x00, 0x12, 0x0e, 0x0a, 0x08, 0x4d, 0x41, 0x58, 0x5f, 0x53, 0x49, 0x5a, 0x45, 0x10, 0xff, 0xff,
	0x03, 0x2a, 0x81, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x55, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01, 0x4b,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x5f, 0x4e, 0x4f, 0x44,
	0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4e, 0x4f,
	0x44, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x4f, 0x4f, 0x4b, 0x55, 0x50, 0x10, 0x04,
	0x12, 0x0d, 0x0a, 0x09, 0x47, 0x45, 0x54, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x53, 0x10, 0x05, 0x12,
	0x0d, 0x0a, 0x09, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x53, 0x54, 0x5f, 0x4b, 0x10, 0x06, 0x12, 0x0b,
	0x0a, 0x07, 0x42, 0x55, 0x43, 0x4b, 0x45, 0x54, 0x53, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x49,
	0x4e, 0x49, 0x54, 0x10, 0x08, 0x2a, 0x2f, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54,
	0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x42, 0x16, 0x5a, 0x14, 0x63, 0x73, 0x65, 0x35, 0x38, 0x36,
	0x2e, 0x6b, 0x64, 0x68, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x64, 0x68, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_kdht_router_proto_rawDescOnce sync.Once
	file_api_kdht_router_proto_rawDescData = file_api_kdht_router_proto_rawDesc
)

func file_api_kdht_router_proto_rawDescGZIP() []byte {
	file_api_kdht_router_proto_rawDescOnce.Do(func() {
		file_api_kdht_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_kdht_router_proto_rawDescData)
	})
	return file_api_kdht_router_proto_rawDescData
}

var file_api_kdht_router_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_kdht_router_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_kdht_router_proto_goTypes = []interface{}{
	(RouteMessage)(0),     // 0: kdht.RouteMessage
	(RouteType)(0),        // 1: kdht.RouteType
	(RouteError)(0),       // 2: kdht.RouteError
	(*RouteRequest)(nil),  // 3: kdht.RouteRequest
	(*RouteResponse)(nil), // 4: kdht.RouteResponse
	(*NodeInfo)(nil),      // 5: kdht.NodeInfo
}
var file_api_kdht_router_proto_depIdxs = []int32{
	1, // 0: kdht.RouteRequest.type:type_name -> kdht.RouteType
	5, // 1: kdht.RouteRequest.node:type_name -> kdht.NodeInfo
	1, // 2: kdht.RouteResponse.type:type_name -> kdht.RouteType
	2, // 3: kdht.RouteResponse.error:type_name -> kdht.RouteError
	5, // 4: kdht.RouteResponse.node:type_name -> kdht.NodeInfo
	5, // 5: kdht.RouteResponse.nodes:type_name -> kdht.NodeInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_kdht_router_proto_init() }
func file_api_kdht_router_proto_init() {
	if File_api_kdht_router_proto != nil {
		return
	}
	file_api_kdht_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_kdht_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_kdht_router_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_kdht_router_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_kdht_router_proto_goTypes,
		DependencyIndexes: file_api_kdht_router_proto_depIdxs,
		EnumInfos:         file_api_kdht_router_proto_enumTypes,
		MessageInfos:      file_api_kdht_router_proto_msgTypes,
	}.Build()
	File_api_kdht_router_proto = out.File
	file_api_kdht_router_proto_rawDesc = nil
	file_api_kdht_router_proto_goTypes = nil
	file_api_kdht_router_proto_depIdxs = nil
}
